//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18331
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.UniSocialService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UniSocialService.IUniSocial")]
    public interface IUniSocial {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniSocial/StartNewTask", ReplyAction="http://tempuri.org/IUniSocial/StartNewTaskResponse")]
        void StartNewTask(Worker.Model.CollectTask CollectTask);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniSocial/StartNewTask", ReplyAction="http://tempuri.org/IUniSocial/StartNewTaskResponse")]
        System.Threading.Tasks.Task StartNewTaskAsync(Worker.Model.CollectTask CollectTask);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniSocial/GetTasks", ReplyAction="http://tempuri.org/IUniSocial/GetTasksResponse")]
        System.Collections.Generic.List<Worker.Model.CollectTask> GetTasks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniSocial/GetTasks", ReplyAction="http://tempuri.org/IUniSocial/GetTasksResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Worker.Model.CollectTask>> GetTasksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniSocial/GetCurrentTaskCount", ReplyAction="http://tempuri.org/IUniSocial/GetCurrentTaskCountResponse")]
        int GetCurrentTaskCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniSocial/GetCurrentTaskCount", ReplyAction="http://tempuri.org/IUniSocial/GetCurrentTaskCountResponse")]
        System.Threading.Tasks.Task<int> GetCurrentTaskCountAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUniSocialChannel : Web.UniSocialService.IUniSocial, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UniSocialClient : System.ServiceModel.ClientBase<Web.UniSocialService.IUniSocial>, Web.UniSocialService.IUniSocial {
        
        public UniSocialClient() {
        }
        
        public UniSocialClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UniSocialClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UniSocialClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UniSocialClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void StartNewTask(Worker.Model.CollectTask CollectTask) {
            base.Channel.StartNewTask(CollectTask);
        }
        
        public System.Threading.Tasks.Task StartNewTaskAsync(Worker.Model.CollectTask CollectTask) {
            return base.Channel.StartNewTaskAsync(CollectTask);
        }
        
        public System.Collections.Generic.List<Worker.Model.CollectTask> GetTasks() {
            return base.Channel.GetTasks();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Worker.Model.CollectTask>> GetTasksAsync() {
            return base.Channel.GetTasksAsync();
        }
        
        public int GetCurrentTaskCount() {
            return base.Channel.GetCurrentTaskCount();
        }
        
        public System.Threading.Tasks.Task<int> GetCurrentTaskCountAsync() {
            return base.Channel.GetCurrentTaskCountAsync();
        }
    }
}
